image: docker:19.03.12

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - docker login -u "$CI_JOB_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t registry.gitlab.com/car.margiotta/pathfinder2-telegram .
    - docker push registry.gitlab.com/car.margiotta/pathfinder2-telegram

unit-test-job:
  stage: test
  script:
    - docker run registry.gitlab.com/car.margiotta/pathfinder2-telegram "inventory_test"

